version: 2
jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker build -t blesswinsamuel/git:latest .
      - run: docker push blesswinsamuel/git:latest
